package serve

import (
	"context"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/cangyunye/go-owl-migrate/internal/config"
	"github.com/cangyunye/go-owl-migrate/internal/dbconn"
	md "github.com/cangyunye/go-owl-migrate/internal/metadata"
	"github.com/cangyunye/go-owl-migrate/internal/metadata/extractor"
	"github.com/cangyunye/go-owl-migrate/internal/paths"
	"github.com/cangyunye/go-owl-migrate/internal/service"
)

func (s *Server) handleExportMetadata(w http.ResponseWriter, r *http.Request) {
	var req struct {
		Source  config.DBConfig `json:"source"`
		Format  string          `json:"format"`
		Scope   string          `json:"scope"`
		Objects string          `json:"objects"`
	}
	if !decodeJSON(w, r, &req, maxBodyBytes) {
		return
	}

	s.mu.RLock()
	cfg := s.cfg
	s.mu.RUnlock()

	src := req.Source
	if src.Type == "" {
		src = cfg.Source
	}
	metaSrc := src
	if resolved, refSchema, err := s.resolveDSNRef(src.DSN); err != nil {
		writeError(w, http.StatusBadRequest, "data source: "+err.Error())
		return
	} else {
		src.DSN = resolved
		if src.Schema == "" {
			src.Schema = refSchema
		}
	}
	if src.DSN == "" {
		writeError(w, http.StatusBadRequest, "source.dsn is required for metadata export")
		return
	}

	format := req.Format
	if format == "" {
		format = "csv"
	}
	if format != "csv" && format != "xlsx" && format != "sql" {
		writeError(w, http.StatusBadRequest, "unsupported format: "+format+" (use csv, xlsx, or sql)")
		return
	}

	// 统一范围解析（CLI 与 serve 同源）：all | schema:NAME | table:GLOB | schema:NAME:table:GLOB
	targetSchema, patterns, err := service.ParseMetadataExportScope(req.Scope, src.Schema)
	if err != nil {
		writeError(w, http.StatusBadRequest, err.Error())
		return
	}

	var objects md.ObjectSet
	if strings.TrimSpace(req.Objects) != "" {
		if objects, err = md.ParseObjectTypes(req.Objects); err != nil {
			writeError(w, http.StatusBadRequest, err.Error())
			return
		}
		// 能力校验（ADR-004）：CLI 报错 / 请求返回明确错误；UI 另按能力禁用选项
		caps := extractor.Capabilities(src.Type)
		var unsupported []string
		for _, o := range md.AllObjectTypes() {
			if objects.Contains(o) && !caps.Contains(o) {
				unsupported = append(unsupported, string(o))
			}
		}
		if len(unsupported) > 0 {
			writeError(w, http.StatusBadRequest, fmt.Sprintf("source %q does not support object type(s): %s", src.Type, strings.Join(unsupported, ",")))
			return
		}
	}
	if format == "sql" && service.TargetTypeFamily(src.Type) != "oracle" {
		writeError(w, http.StatusBadRequest, fmt.Sprintf("format sql 仅 oracle 家族有意义（当前 source=%s）；请使用 csv", src.Type))
		return
	}

	db, err := service.OpenDB(src)
	if err != nil {
		writeError(w, http.StatusBadRequest, "connect to source: "+err.Error())
		return
	}
	defer db.Close()

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	if err := db.PingContext(ctx); err != nil {
		writeError(w, http.StatusBadRequest, "ping source: "+err.Error())
		return
	}

	sm, err := extractor.Extract(db, dbconn.MetadataSourceType(src), targetSchema)
	if err != nil {
		writeError(w, http.StatusInternalServerError, "extract metadata: "+err.Error())
		return
	}

	// 范围选择（附随随表；独立对象仅整 schema；零命中报相近名建议，ADR-002/004）
	if len(patterns) > 0 {
		if sm, err = (md.ObjectSelector{Schemas: patterns}).Select(sm); err != nil {
			writeError(w, http.StatusBadRequest, err.Error())
			return
		}
	}

	outDir := filepath.Join(paths.TempDir(), "metadata-"+randSuffix())
	os.MkdirAll(outDir, 0755)

	var files []string
	switch format {
	case "csv":
		files, err = service.ExportMetadataFiles(outDir, sm, objects)
	case "sql":
		files, err = exportMetadataSQL(outDir, src.Type, sm, sm.GetTables(), targetSchema)
	default:
		files, err = service.ExportMetadataFiles(outDir, sm, objects)
	}
	if err != nil {
		writeError(w, http.StatusInternalServerError, "export metadata: "+err.Error())
		return
	}

	tables := sm.GetTables()
	meta := sourceMetaFrom(metaSrc, targetSchema)
	meta.Detail = map[string]any{
		"format":      format,
		"scope":       req.Scope,
		"table_count": len(tables),
		"file_count":  len(files),
	}
	if err := s.recordGenOutput("metadata", outDir, meta); err != nil {
		writeError(w, http.StatusInternalServerError, "record output: "+err.Error())
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{
		"output_dir":  outDir,
		"format":      format,
		"table_count": len(tables),
		"count":       len(files),
		"files":       readGenFiles(files),
	})
}

func exportMetadataSQL(dir string, dbType string, sm *md.SchemaModel, tables []*md.TableDef, schema string) ([]string, error) {
	p := filepath.Join(dir, "metadata.sql")
	f, err := os.Create(p)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	dialect := strings.ToLower(dbType)
	q := func(s string) string {
		if dialect == "mysql" {
			return "`" + s + "`"
		}
		return `"` + s + `"`
	}

	fmt.Fprintf(f, "-- Metadata export for schema %s\n", schema)
	fmt.Fprintf(f, "-- Dialect: %s\n", dbType)
	fmt.Fprintf(f, "-- Generated by owl-migrate web UI\n\n")

	for _, tbl := range tables {
		tableOwner := tbl.Owner
		if tableOwner == "" {
			tableOwner = schema
		}
		fmt.Fprintf(f, "INSERT INTO dba_tables (%s, %s, %s) VALUES (%s, %s, %s);\n",
			q("OWNER"), q("TABLE_NAME"), q("TABLE_TYPE"),
			q(tableOwner), q(tbl.TableName), q(tbl.TableType))
	}

	for _, tbl := range tables {
		for _, col := range tbl.GetColumns() {
			nullable := "Y"
			if col.Nullable == "NO" {
				nullable = "N"
			}
			fmt.Fprintf(f, "INSERT INTO dba_tab_columns (%s, %s, %s, %s, %s, %s) VALUES (%s, %s, %s, %d, %s, %s);\n",
				q("OWNER"), q("TABLE_NAME"), q("COLUMN_NAME"),
				q("DATA_TYPE"), q("DATA_LENGTH"), q("NULLABLE"),
				q(schema), q(tbl.TableName), q(col.ColumnName),
				col.DataLength, q(col.DataType), q(nullable))
		}
	}

	for _, tbl := range tables {
		for _, pk := range tbl.GetPrimaryKeys() {
			fmt.Fprintf(f, "INSERT INTO dba_constraints (%s, %s, %s, %s, %s) VALUES (%s, %s, %s, 'P', 'ENABLED');\n",
				q("OWNER"), q("TABLE_NAME"), q("CONSTRAINT_NAME"), q("CONSTRAINT_TYPE"), q("STATUS"),
				q(schema), q(tbl.TableName), q(pk.ConstraintName))
			fmt.Fprintf(f, "INSERT INTO dba_cons_columns (%s, %s, %s, %s, %s) VALUES (%s, %s, %s, %s, %d);\n",
				q("OWNER"), q("CONSTRAINT_NAME"), q("TABLE_NAME"), q("COLUMN_NAME"), q("COLUMN_POSITION"),
				q(schema), q(pk.ConstraintName), q(tbl.TableName), q(pk.ColumnName), pk.OrdinalPosition)
		}
	}

	for _, tbl := range tables {
		for _, idx := range tbl.GetIndexes() {
			fmt.Fprintf(f, "INSERT INTO dba_indexes (%s, %s, %s, %s, %s) VALUES (%s, %s, %s, %s, %s);\n",
				q("OWNER"), q("INDEX_NAME"), q("TABLE_NAME"), q("UNIQUENESS"), q("INDEX_TYPE"),
				q(schema), q(idx.IndexName), q(tbl.TableName), q(idx.Uniqueness), q(idx.IndexType))
			fmt.Fprintf(f, "INSERT INTO dba_ind_columns (%s, %s, %s, %s, %s) VALUES (%s, %s, %s, %s, %d);\n",
				q("INDEX_OWNER"), q("INDEX_NAME"), q("TABLE_NAME"), q("COLUMN_NAME"), q("COLUMN_POSITION"),
				q(schema), q(idx.IndexName), q(tbl.TableName), q(idx.ColumnName), idx.OrdinalPosition)
		}
	}

	for _, v := range sm.GetViews() {
		fmt.Fprintf(f, "INSERT INTO dba_views (%s, %s, %s) VALUES (%s, %s, %s);\n",
			q("OWNER"), q("VIEW_NAME"), q("TEXT"),
			q(v.ViewSchema), q(v.ViewName), q(v.ViewDefinition))
	}

	for _, seq := range sm.GetSequences(schema) {
		fmt.Fprintf(f, "INSERT INTO dba_sequences (%s, %s, %s, %s, %s) VALUES (%s, %s, %d, %d, %d);\n",
			q("SEQUENCE_OWNER"), q("SEQUENCE_NAME"), q("MIN_VALUE"), q("MAX_VALUE"), q("INCREMENT_BY"),
			q(schema), q(seq.SequenceName), seq.MinValue, seq.MaxValue, seq.IncrementBy)
	}

	fmt.Fprintf(f, "\n-- %d tables, %d views, %d sequences exported\n",
		len(tables), len(sm.GetViews()), len(sm.GetSequences(schema)))

	return []string{p}, nil
}
