package cmd

import (
	"fmt"
	"os"
	"slices"
	"strings"

	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"

	"github.com/cangyunye/go-owl-migrate/internal/config"
)

func initCmd() *cobra.Command {
	var (
		sourceType   string
		sourceDSN    string
		sourceSchema string
		targetType   string
		targetDSN    string
		targetSchema string
		outputFile   string
		metadataType string
	)

	cmd := &cobra.Command{
		Use:   "init",
		Short: "Generate a configuration file from source/target database parameters",
		Long: `Generates a complete, ready-to-use YAML configuration file from
command-line parameters specifying source and target databases.

This eliminates the need to manually craft configuration files.
After generating the config, you can run other commands with -c <file>.

Examples:
  # Generate config for an Oracle-to-PostgreSQL migration
  owl-migrate init --source-type oracle --source-dsn "oracle://user:pass@host:1521/service" \
    --source-schema SCOTT --target-type postgres \
    --target-dsn "postgres://user:pass@localhost:5432/migrate" --target-schema public

  # Generate config for MySQL to GoldenDB with CSV metadata
  owl-migrate init --source-type mysql --source-dsn "user:pass@tcp(host:3306)/db" \
    --source-schema mydb --target-type goldendb-mysql --metadata-type csv`,
		RunE: func(cmd *cobra.Command, args []string) error {
			// Validate source type
			if sourceType == "" {
				return fmt.Errorf("--source-type is required")
			}
			if !config.ValidDialects[strings.ToLower(sourceType)] {
				return fmt.Errorf("unsupported --source-type %q: must be one of %v",
					sourceType, sortedDialectKeys())
			}

			// Validate target type
			if targetType == "" {
				return fmt.Errorf("--target-type is required")
			}
			if !config.ValidDialects[strings.ToLower(targetType)] {
				return fmt.Errorf("unsupported --target-type %q: must be one of %v",
					targetType, sortedDialectKeys())
			}

			// Validate metadata type
			mt := strings.ToLower(metadataType)
			if !config.ValidMetadataTypes[mt] {
				return fmt.Errorf("unsupported --metadata-type %q: must be one of %v",
					metadataType, sortedMetadataKeys())
			}

			// When using live database metadata, source DSN and schema are required
			if mt == "database" {
				if sourceDSN == "" {
					return fmt.Errorf("--source-dsn is required when --metadata-type is 'database'")
				}
				if sourceSchema == "" {
					return fmt.Errorf("--source-schema is required when --metadata-type is 'database'")
				}
			}

			// Build config from parameters
			cfg := buildConfig(sourceType, sourceDSN, sourceSchema, targetType, targetDSN, targetSchema, mt)

			// Marshal to YAML with a comment header
			buf, err := yaml.Marshal(cfg)
			if err != nil {
				return fmt.Errorf("marshal config: %w", err)
			}

			header := "# Auto-generated by owl-migrate init\n" +
				"# Edit this file to fine-tune migration settings, then run:\n" +
				"#   owl-migrate validate -c " + outputFile + "\n" +
				"#   owl-migrate gen-ddl  -c " + outputFile + "\n" +
				"#   owl-migrate migrate  -c " + outputFile + "\n\n"

			content := append([]byte(header), buf...)

			// Write output file
			if err := os.WriteFile(outputFile, content, 0644); err != nil {
				return fmt.Errorf("write config to %q: %w", outputFile, err)
			}

			fmt.Printf("Configuration written to %s\n", outputFile)
			fmt.Println()
			fmt.Printf("  Source: %s (schema: %s)\n", cfg.Source.Type, cfg.Source.Schema)
			fmt.Printf("  Target: %s (schema: %s)\n", cfg.Target.Type, cfg.Target.Schema)
			fmt.Printf("  Metadata type: %s\n", cfg.Metadata.Type)
			fmt.Printf("  DDL target dialect: %s\n", cfg.DDL.TargetDialect)
			fmt.Println()
			fmt.Println("You can now run:")
			fmt.Printf("  owl-migrate gen-ddl -c %s\n", outputFile)
			if cfg.Source.DSN != "" {
				fmt.Printf("  owl-migrate migrate -c %s\n", outputFile)
			}
			return nil
		},
	}

	cmd.Flags().StringVarP(&sourceType, "source-type", "s", "", "source database type (oracle/postgres/mysql/goldendb/oceanbase/etc.)")
	cmd.Flags().StringVar(&sourceDSN, "source-dsn", "", "source database DSN")
	cmd.Flags().StringVar(&sourceSchema, "source-schema", "", "source database schema/database name")
	cmd.Flags().StringVarP(&targetType, "target-type", "t", "", "target database type")
	cmd.Flags().StringVar(&targetDSN, "target-dsn", "", "target database DSN (optional for DDL-only workflows)")
	cmd.Flags().StringVar(&targetSchema, "target-schema", "", "target database schema (defaults to source-schema if empty)")
	cmd.Flags().StringVarP(&outputFile, "output", "o", "./migrate.yaml", "output configuration file path")
	cmd.Flags().StringVarP(&metadataType, "metadata-type", "m", "database", "metadata source: csv or database")

	return cmd
}

// buildConfig constructs a fully-populated Config from init command parameters.
func buildConfig(srcType, srcDSN, srcSchema, tgtType, tgtDSN, tgtSchema, metaType string) *config.Config {
	// Normalize
	srcType = strings.ToLower(srcType)
	tgtType = strings.ToLower(tgtType)

	// If target schema not specified, use source schema
	if tgtSchema == "" {
		tgtSchema = srcSchema
	}

	// Build schema mapping
	schemaMapping := make(map[string]string)
	if srcSchema != "" {
		schemaMapping[srcSchema] = tgtSchema
	}

	// CSV path default
	csvPath := ""
	if metaType == "csv" {
		csvPath = "./testdata/csv/"
	}

	return &config.Config{
		General: config.GeneralConfig{
			LogLevel:  "info",
			LogFormat: "text",
		},
		Metadata: config.MetadataConfig{
			Type: metaType,
			CSV: config.CSVConfig{
				Path:               csvPath,
				Delimiter:          ",",
				Encoding:           "utf-8",
				HasHeader:          true,
				NullMarker:         "\\N",
				ColumnNameMatching: "case_insensitive",
			},
		},
		Source: config.DBConfig{
			Type:   srcType,
			DSN:    srcDSN,
			Schema: srcSchema,
		},
		Target: config.DBConfig{
			Type:   tgtType,
			DSN:    tgtDSN,
			Schema: tgtSchema,
		},
		DDL: config.DDLConfig{
			OutputDir:          "./output/ddl/",
			TargetDialect:      tgtType,
			IncludeComments:    true,
			IncludeIfNotExists: true,
			SplitByObject:      true,
			SchemaMapping:      schemaMapping,
			TableFilter: config.TableFilterConfig{
				Include: []string{"*"},
				Exclude: config.TableExcludeConfig{
					Glob:    []string{"*_LOG", "TMP_*"},
					Schemas: []string{"SYS", "SYSTEM"},
				},
			},
			TypeOverrides: make(map[string]string),
			Partition: config.PartitionConfig{
				Migrate: false,
			},
			NoQuoteIdentifiers: false,
		},
		SelectGen: config.SelectGenConfig{
			OutputDir: "./output/select/",
			Batch: config.BatchConfig{
				Method:   "cursor",
				PageSize: 5000,
			},
		},
		Export: config.ExportConfig{
			OutputDir: "./output/data/",
			Format:    "csv",
			CSV: config.ExportCSVConfig{
				Delimiter:          ",",
				QuoteChar:          "\"",
				Encoding:           "utf-8",
				Header:             true,
				NullRepresentation: "\\N",
			},
			Batch: config.BatchConfig{
				Method:   "cursor",
				PageSize: 5000,
			},
			Parallel: config.ParallelConfig{
				Enabled:    true,
				MaxWorkers: 4,
			},
			Tables: config.TableListConfig{
				Include: []string{"*"},
			},
		},
		Import: config.ImportConfig{
			SourceDir: "./output/data/",
			Format:    "csv",
			CSV: config.ImportCSVConfig{
				Delimiter:  ",",
				HasHeader:  true,
				NullMarker: "\\N",
			},
			Target: config.ImportTargetConfig{
				TruncateBefore: false,
			},
			Batch: config.ImportBatchConfig{
				CommitInterval: 1000,
				ErrorPolicy:    "skip_row",
			},
			Parallel: config.ParallelConfig{
				Enabled:            true,
				MaxWorkers:         4,
				RespectForeignKeys: true,
			},
			DataTransforms: config.DataTransforms{
				DatetimeFormat: "yyyyMMddHHmmss",
				TrimStrings:    true,
				NullIf:         []string{"NULL", "null", "\\N"},
			},
		},
	}
}

// sortedDialectKeys returns the valid dialect names in alphabetical order.
func sortedDialectKeys() []string {
	keys := make([]string, 0, len(config.ValidDialects))
	for k := range config.ValidDialects {
		keys = append(keys, k)
	}
	slices.Sort(keys)
	return keys
}

// sortedMetadataKeys returns the valid metadata type names in alphabetical order.
func sortedMetadataKeys() []string {
	keys := make([]string, 0, len(config.ValidMetadataTypes))
	for k := range config.ValidMetadataTypes {
		keys = append(keys, k)
	}
	slices.Sort(keys)
	return keys
}
