package cdc

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"
)

// RunnerTemplate describes how to execute a batch file via an external client.
type RunnerTemplate struct {
	// Command is the client binary (e.g. "sqlplus", "psql").
	Command string
	// ArgsTemplate is the argument template with a {file} placeholder for the
	// batch file path (e.g. `{user}/{pw}@{host}:{port} -f {file}`).
	ArgsTemplate string
	// Pending, Done, Failed are the batch directories.
	Pending, Done, Failed string
}

// RenderRunner renders a POSIX sh script that scans the pending directory in
// sequence order (by filename), executes each file via the client, and moves it
// to done/ on success or failed/ on error (without pausing).
func (r RunnerTemplate) RenderRunner() (string, error) {
	script := `#!/bin/sh
# Generated by owl-migrate online init-runner. Executes pending batch files in
# sequence order and moves each to done/ (success) or failed/ (error).
PENDING={{.Pending}}
DONE={{.Done}}
FAILED={{.Failed}}
mkdir -p "$DONE" "$FAILED"

for f in "$PENDING"/*.sql; do
  [ -e "$f" ] || continue
  name=$(basename "$f")
  if {{.Invocation}}; then
    mv "$f" "$DONE/$name"
    echo "OK   $name"
  else
    err=$?
    mv "$f" "$FAILED/$name"
    echo "FAIL $name (exit $err)" >&2
  fi
done
`
	tmpl, err := template.New("runner").Parse(script)
	if err != nil {
		return "", fmt.Errorf("parse runner template: %w", err)
	}
	data := struct {
		Pending, Done, Failed string
		Invocation            string
	}{
		Pending:    r.Pending,
		Done:       r.Done,
		Failed:     r.Failed,
		Invocation: r.invocation(),
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("render runner: %w", err)
	}
	return buf.String(), nil
}

// invocation builds the shell command that substitutes {file} with the pending
// path. The file path is the loop variable $f.
func (r RunnerTemplate) invocation() string {
	args := strings.ReplaceAll(r.ArgsTemplate, "{file}", `"$f"`)
	base := r.Command
	if args != "" {
		base += " " + args
	}
	return base
}
